### ISSUE TITLE
windyfixer tool

### ISSUE THREAD

**Issue by clivej** [matthewwall/weewx-windy#8]
Any chance of a tool like wunderfixer which can be used to republish missed Windy records? (ie bad internet connection prevents record being published when retrieved from station)

**Comment by matthewwall** [comment]
i've been working on a more general approach that would work with *any* online service (using the weewx uploader extensions), not just windy.com.  the code has been languishing on a private subversion repository - i'm in the process of converting that to a gitlab instance so that more people can participate...
